name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: mikeparcewski/wicked-ci/.github/workflows/node-ci.yml@6573ae1b5eeb50468193308750c08ceeafde8039 # v1.1.1
    with:
      test_working_dir: server

  wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: lts/*
      - run: cd server && npm install
      - run: cd server && npm run gen:wiki:check
      - run: cd server && npm run lint:wiki:strict
